---
baseURL: https://naughty-mestorf-0456d0.netlify.app/
title: Qauzativ website template
theme: educenter-hugo
paginate: '4'
summaryLength: '40'
disableLanguages: []
params:
  address: https://github.com/Qauzativ?tab=repositories
  author: Qauzativ
  contact_form_action: "#"
  cookies:
    enable: 
    expire_days: 100
  description: Description in config.yaml file
  email: info@qauzativ.com
  google_analitycs_id: ''
  logo: images/logo.png
  mobile: "+0 000 000 0000"
  plugins:
    css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/slick/slick.css
    - link: plugins/animate/animate.css
    - link: plugins/venobox/venobox.css
    - link: plugins/themify-icons/themify-icons.css
    js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/venobox/venobox.min.js
    - link: plugins/filterizr/jquery.filterizr.min.js
    - link: plugins/google-map/gmap.js
  preloader:
    enable: 
    preloader: images/preloader.gif
  social:
  - icon: ti-github
    link: "#"
    title: github
  - icon: ti-linkedin
    link: "#"
    title: linkedin
  subscription:
    enable: 
    mailchimp_form_action: https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074
    mailchimp_form_name: b_463ee871f45d2d93748e77cad_a0a2c6d074
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2021 [Qauzativ](https://www.qauzativ.com)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      footer:
      - name: teacher
        url: teacher
      - name: notice
        url: notice
      - name: event
        url: event
      - name: scholarship
        url: scholarship
      - name: research
        url: research
      main:
      - name: Why Qauzativ?
        url: product
        weight: 1
      - name: Training = Solutions
        url: training
        weight: 2
      - hasChildren: true
        name: Info
        weight: 3
      - name: About
        parent: Info
        url: about
      - name: FAQ
        parent: Info
        url: faq
      - name: Blog
        parent: Info
        url: blog
      - name: Contact
        parent: Info
        url: contact
      - name: Events
        parent: Info
        url: event
      - name: course
        url: course
        weight: 11
      - hasChildren: true
        name: Pages
        weight: 12
      - name: teacher
        parent: Pages
        url: teacher
      - name: notice
        parent: Pages
        url: notice
      - name: event
        parent: Pages
        url: event
      - name: scholarship
        parent: Pages
        url: scholarship
      - name: research
        parent: Pages
        url: research
      - name: author
        parent: Pages
        url: author
